export enum DatabaseName {
    Role = "Role",
    Admin = "Admin",
    FcmDevice = "FcmDevice",
    IspUid = "IspUid",
    Customer = "Customer",
    Device = "Device",
    Group = "Group",
    Plan = "Plan",
    Order = "Order",
    Invoice = "Invoice",
    Transaction = "Transaction",
    paymentGateway = "paymentGateway",
    Config = "Config",
    Template = "Template",
    SmsHistory = "SmsHistory",
    EmailHistory = "EmailHistory",
    NotificationHistory = "NotificationHistory",
    Ott = "Ott",
    NewJoining = "NewJoining",
}