export enum DatabaseName {
    Role = "Role",
    Admin = "Admin",
    Attendance = "Attendance",
    TableStructure = "TableStructure",
    MediaFile = "MediaFile",
    Document = "Document",
    FcmDevice = "FcmDevice",
    IspUid = "IspUid",
    Customer = "Customer",
    Device = "Device",
    Group = "Group",
    Plan = "Plan",
    Order = "Order",
    Invoice = "Invoice",
    Transaction = "Transaction",
    paymentGateway = "paymentGateway",
    Config = "Config",
    Template = "Template",
    SmsHistory = "SmsHistory",
    EmailHistory = "EmailHistory",
    NotificationHistory = "NotificationHistory",
    Ott = "Ott",
    NewJoining = "NewJoining",
    LoginLog = "LoginLog",
}