export declare enum DatabaseName {
    Role = "Role",
    Admin = "Admin",
    IspUid = "IspUid",
    Customer = "Customer",
    Device = "Device",
    Group = "Group",
    Plan = "Plan",
    Order = "Order",
    Invoice = "Invoice",
    Transaction = "Transaction",
    paymentGateway = "paymentGateway",
    Config = "Config",
    SmsTemplate = "SmsTemplate",
    EmailTemplate = "EmailTemplate",
    NotificationTemplate = "NotificationTemplate",
    SmsHistory = "SmsHistory",
    EmailHistory = "EmailHistory",
    NotificationHistory = "NotificationHistory",
    Ott = "Ott"
}
