export const Paths = {
    login: '/login',
    customers: 'customers',
    customersPendingKYC: 'customers/pendingKYC',
    newJoining: 'customers/new-joining',
    staff: 'management/staffs',
    roles: 'management/roles',
    addGroup: 'settings/groups/add-new',
    groupList: 'settings/groups',
    ottListing: 'otts',
    addOtt: 'otts/add-new',
    planListing: 'plans',
    addPlan: 'plans/add-new',
    attendanceCalender: 'management/attendance',
    companyProfile: 'settings/company/profile',
    deviceList: 'devices',
    deviceMapping: 'devices/mapping',
    devicetypesListing: 'settings/device/device-type',
    templates: 'settings/communication/templates',
    services: 'services',
    invoices: 'invoices',
    invoiceConfig: 'settings/invoice/config',
    paymentGateway: '/settings/paymentGateway/'
}