export const Paths = {
    login: '/login',
    customers: 'customers',
    customersPendingKYC: 'customers/pendingKYC',
    newJoining: 'customers/new-joining',
    staff: 'management/staffs',
    roles: 'management/roles',
    addGroup: 'settings/groups/add-new',
    groupList: 'settings/groups',
    ottListing: 'services/otts',
    addOtt: 'services/otts/add-new',
    planListing: 'services/plans',
    addPlan: 'services/plans/add-new',
    attendanceCalender: 'management/attendance',
    companyProfile: 'settings/company/profile',
    deviceList: 'devices',
    deviceMapping: 'devices/mapping',
    devicetypesListing:'settings/device/device-type',
    templates:'settings/communication/templates'
}