export * from './types/activePlans.interface'
export * from './types/admin.interface'
export * from './types/common.interface'
export * from './types/config.interface'
export * from './types/customers.interface'
export * from './types/database.interfaces'
export * from './types/device.interface'
export * from './types/emailTemplates.interface'
export * from './types/group.interface'
export * from './types/notificationTemplates.interface'
export * from './types/invoice.interface'
export * from './types/ott.interface'
// all good