name: "Publish Package"
on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}

jobs:
  versionControl:
    name: Bump and Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bump and Tag
        id: bump_and_tag
        uses: konsentus/action.bump-version-and-tag@master

      - name: Configure Git
        run: |
          git config user.email "$(git show -s --format=%ae)"
          git config user.name "$(git show -s --format=%an)"
      - uses: kellyselden/move-semver-tags-action@v2

  publish:
    needs: versionControl
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org
      - name: Install Packages
        run: npm install
      - name: Package Build
        run: npm run build
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
